apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp

spec:
  containers:
    - name: redis-db
      image: redis
      readinessProbe:
        tcpSocket:
          port: 3306
      livenessProbe:
        tcpSocket:
          port: 3306